server:
  port: 9080
spring:
  application:
    name: service-gateway
  config:
    import: optional:configserver:http://localhost:9090
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-url: http://localhost:${server.port}
        heartbeat:
          enabled: true
    gateway:
      routes:
        - id: member_route
          uri: http://localhost:8091
          predicates:
            - Path=/member/**
        - id: product_route
          uri: http://localhost:8092
          predicates:
            - Path=/product/**
        - id: order_route
          uri: http://localhost:8093
          predicates:
            - Path=/order/**
  profiles:
    active: dev
