server:
  port: 8092
spring:
  application:
    name: service-product
  config:
    import: optional:configserver:http://localhost:9090
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-url: http://localhost:${server.port}
        heartbeat:
          enabled: true
  profiles:
    active: dev
