version: "3"
services:
  mysql:
    image: mysql:8.0.32
    container_name: gitops-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    command: --max_connections=600
    volumes:
      - "../data/docker/mysql-data:/var/lib/mysql"
      - "../data/sql/ddl.sql:/docker-entrypoint-initdb.d/1.sql:ro"
      - "../data/sql/init.sql:/docker-entrypoint-initdb.d/2.sql:ro"
    healthcheck:
      interval: 20s
      test: mysql -h 127.0.0.1 -u root --password=123456 -e "SELECT * FROM gitops.member ORDER BY id LIMIT 1;"

  gitops-backend:
    image: xprogrammer/gitops-backend:v1.0.0
    container_name: gitops-backend
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 60s

  gitops-frontend:
    image: xprogrammer/gitops-frontend:v1.0.0
    container_name: gitops-frontend
    depends_on:
      gitops-backend:
        condition: service_started
    ports:
      - "30080:30080"
