apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: sbc2nd
  labels:
    app: hello-docker-console
data:
  nginx.conf: |
    server {
        listen       80;
        server_name  localhost;
        location / {
            root   html;
            index  index.html index.htm;
        }
        location /api/ {
            proxy_set_header Access-Control-Allow-Origin *;
            proxy_pass http://hello-docker-order:8080/; #设置监控后端启动的端口
            rewrite  ^.+api/?(.*)$ /$1 break;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker-console
  namespace: sbc2nd
  labels:
    app: hello-docker-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-docker-console
  template:
    metadata:
      labels:
        app: hello-docker-console
    spec:
      hostname: hello-docker-console
      dnsConfig:
        options:
          - name: ndots
            value: "2"
        searches:
          - hello-docker-console.sbc2nd.svc.cluster.local
          - sbc2nd.svc.cluster.local
      containers:
        - name: hello-docker-console
          image: xprogrammer/hello-docker-console
          ports:
            - protocol: TCP
              containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: ORDER_SERVICE_URL
              value: http://hello-docker-order
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d
              readOnly: true
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
      initContainers:
        - name: wait-for-hello-docker-order
          image: busybox:1.36.0-uclibc
          command: ['sh', '-c', 'until nslookup hello-docker-order.sbc2nd.svc.cluster.local; do echo waiting for hello-docker-order; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: hello-docker-console
  namespace: sbc2nd
  labels:
    app: hello-docker-console
spec:
  selector:
    app: hello-docker-console
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
