apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: sbc2nd
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      hostname: rabbitmq
      dnsConfig:
        options:
          - name: ndots
            value: "2"
        searches:
          - rabbitmq.sbc2nd.svc.cluster.local
          - sbc2nd.svc.cluster.local
      containers:
        - name: rabbitmq
          image: rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"
          ports:
            - containerPort: 5672
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: sbc2nd
  labels:
    app: rabbitmq
spec:
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
  selector:
    app: rabbitmq
  type: ClusterIP
