apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
  labels:
    app: mysql
data:
  ddl.sql: |
    DROP DATABASE IF EXISTS hellodockerk8s;
    CREATE DATABASE hellodockerk8s;
    USE hellodockerk8s;
    
    -- ----------------------------
    -- Table structure for member
    -- ----------------------------
    DROP TABLE IF EXISTS `member`;
    CREATE TABLE `member`  (
    `id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '主键',
    `member_code` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '会员号',
    `member_name` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '会员名称',
    `member_remark` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '会员说明',
    `member_level` int NULL DEFAULT NULL COMMENT '会员等级',
    PRIMARY KEY (`id`) USING BTREE
    ) ENGINE = InnoDB CHARACTER SET = utf8mb3 COLLATE = utf8mb3_general_ci COMMENT = '会员' ROW_FORMAT = DYNAMIC;
    
    -- ----------------------------
    -- Table structure for order
    -- ----------------------------
    DROP TABLE IF EXISTS `order_info`;
    CREATE TABLE `order_info`  (
    `id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '主键',
    `order_code` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '订单号码',
    `member_id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '会员主键',
    `product_id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '商品主键',
    `order_amount` int NOT NULL COMMENT '订购数量',
    `member_name` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '会员名称，冗余',
    `product_name` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '商品名称，冗余',
    PRIMARY KEY (`id`) USING BTREE
    ) ENGINE = InnoDB CHARACTER SET = utf8mb3 COLLATE = utf8mb3_general_ci COMMENT = '订单' ROW_FORMAT = DYNAMIC;
    
    -- ----------------------------
    -- Table structure for product
    -- ----------------------------
    DROP TABLE IF EXISTS `product`;
    CREATE TABLE `product`  (
    `id` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '主键',
    `product_code` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '商品编码',
    `product_name` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT '商品名称',
    `product_remark` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL COMMENT '商品说明',
    `product_amount` int NOT NULL COMMENT '库存数量',
    PRIMARY KEY (`id`) USING BTREE
    ) ENGINE = InnoDB CHARACTER SET = utf8mb3 COLLATE = utf8mb3_general_ci COMMENT = '商品' ROW_FORMAT = DYNAMIC;
  init.sql: |
    USE hellodockerk8s;
    -- ----------------------------
    -- Records of member
    -- ----------------------------
    INSERT INTO `member` VALUES ('AG6998', '10010', 'Keven Zhang', '这哥们自己觉得自己长得帅，其实...', 999);
    INSERT INTO `member` VALUES ('LY1113', '10012', 'Lily Huang', '人美心善脾气好...', 888);
    INSERT INTO `member` VALUES ('RY3525', '10011', 'Roy Zhang', '小伙子不错哦~学习很努力', 666);
    
    -- ----------------------------
    -- Records of product
    -- ----------------------------
    INSERT INTO `product` VALUES ('AU9999', '80080', '金条24K1公斤', '纯金砖头1公斤', 999);
    INSERT INTO `product` VALUES ('PC8888', '80081', '超级电脑32T内存', '游戏本，内存贼大，贼耗电', 888);
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      hostname: mysql
      dnsConfig:
        options:
          - name: ndots
            value: "2"
        searches:
          - mysql.default.svc.cluster.local
          - default.svc.cluster.local
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          livenessProbe:
            exec:
              command:
                - sh
                - "-c"
                - "mysqladmin -uroot -p'123456' -P3306 -hlocalhost ping"
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - "-c"
                - "mysql -h 127.0.0.1 -u root --password=123456 -e 'SELECT id FROM hellodockerk8s.member ORDER BY id LIMIT 1;'"
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
      volumes:
        - name: mysql-data
          hostPath:
            path: /run/desktop/mnt/host/d/data/k8s-volumes/mysql-data
            type: DirectoryOrCreate
        - name: init-sql
          configMap:
            name: mysql-init-sql
            items:
              - key: ddl.sql
                path: 1.sql
              - key: init.sql
                path: 2.sql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
