apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker-order
  labels:
    app: hello-docker-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-docker-order
  template:
    metadata:
      labels:
        app: hello-docker-order
    spec:
      containers:
        - name: hello-docker-order
          image: xprogrammer/hello-docker-order
          env:
            - name: REDIS_HOST
              value: redis
            - name: MYSQL_HOST
              value: mysql
            - name: RABBITMQ_HOST
              value: rabbitmq
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: hello-docker-order
  labels:
    app: hello-docker-order
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: hello-docker-order
