apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker-express
  labels:
    app: hello-docker-express
spec:
  selector:
    matchLabels:
      app: hello-docker-express
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-docker-express
    spec:
      containers:
        - name: hello-docker-express
          image: xprogrammer/hello-docker-express
          ports:
            - containerPort: 9090
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hello-docker-express
  labels:
    app: hello-docker-express
spec:
  selector:
    app: hello-docker-express
  ports:
    - name: http
      port: 9090
      targetPort: 9090
