apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker-console
  labels:
    app: hello-docker-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-docker-console
  template:
    metadata:
      labels:
        app: hello-docker-console
    spec:
      hostname: hello-docker-console
      dnsConfig:
        options:
          - name: ndots
            value: "2"
        searches:
          - hello-docker-console.default.svc.cluster.local
          - default.svc.cluster.local
      containers:
        - name: hello-docker-console
          image: xprogrammer/hello-docker-console
          ports:
            - containerPort: 30080
          readinessProbe:
            tcpSocket:
              port: 30080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 30080
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: ORDER_SERVICE_URL
              value: http://hello-docker-order
      initContainers:
        - name: wait-for-hello-docker-order
          image: busybox
          command: ['sh', '-c', 'until nslookup hello-docker-order.default.svc.cluster.local; do echo waiting for hello-docker-order; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: hello-docker-console
  labels:
    app: hello-docker-console
spec:
  selector:
    app: hello-docker-console
  ports:
    - protocol: TCP
      port: 30080
      targetPort: 30080
      nodePort: 30080
  type: NodePort
