apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker-express
  namespace: sbc2nd
  labels:
    app: hello-docker-express
spec:
  selector:
    matchLabels:
      app: hello-docker-express
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-docker-express
    spec:
      hostname: hello-docker-express
      dnsConfig:
        options:
          - name: ndots
            value: "2"
        searches:
          - hello-docker-express.sbc2nd.svc.cluster.local
          - sbc2nd.svc.cluster.local
      containers:
        - name: hello-docker-express
          image: xprogrammer/hello-docker-express
          ports:
            - containerPort: 9090
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 5
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nslookup rabbitmq.sbc2nd.svc.cluster.local; do echo waiting for rabbitmq; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: hello-docker-express
  namespace: sbc2nd
  labels:
    app: hello-docker-express
spec:
  selector:
    app: hello-docker-express
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  type: ClusterIP
