apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-docker-order
  namespace: sbc2nd
  labels:
    app: hello-docker-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-docker-order
  template:
    metadata:
      labels:
        app: hello-docker-order
    spec:
      hostname: hello-docker-order
      dnsConfig:
        options:
          - name: ndots
            value: "2"
        searches:
          - hello-docker-order.sbc2nd.svc.cluster.local
          - sbc2nd.svc.cluster.local
      containers:
        - name: hello-docker-order
          image: xprogrammer/hello-docker-order
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.36.0-uclibc
          command: ['sh', '-c', 'until nslookup rabbitmq.sbc2nd.svc.cluster.local; do echo waiting for rabbitmq; sleep 2; done;']
        - name: wait-for-redis
          image: busybox:1.36.0-uclibc
          command: ['sh', '-c', 'until nslookup redis.sbc2nd.svc.cluster.local; do echo waiting for redis; sleep 2; done;']
        - name: wait-for-mysql
          image: busybox:1.36.0-uclibc
          command: ['sh', '-c', 'until nslookup mysql.sbc2nd.svc.cluster.local; do echo waiting for mysql; sleep 2; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: hello-docker-order
  namespace: sbc2nd
  labels:
    app: hello-docker-order
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: hello-docker-order
  type: ClusterIP
