server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${DB_NAME:gitops}?useUnicode=true&characterEncoding=${DB_ENCODING:utf-8}&serverTimezone=${MYSQL_TIMEZONE:Asia/Shanghai}&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.order.entity