server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysql}:${MYSQL_PORT:3306}/${DB_NAME:hellodockerk8s}?useUnicode=true&characterEncoding=${DB_ENCODING:utf-8}&serverTimezone=${MYSQL_TIMEZONE:Asia/Shanghai}&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: ${REDIS_DATABASE:0}
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password:
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.order.entity